[package]
name = "libublk"
version = "0.1.1"
edition = "2021"
description = "Library for building linux block device in userspace"
authors = ["Ming Lei <tom.leiming@gmail.com>"]
readme = "README.md"
repository = "https://github.com/ming1/libublk-rs"
license = "MIT OR Apache-2.0"
keywords = ["ublk", "io_uring", "userspace", "block", "storage"]
publish = true

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
pkg-config = "0.3"
bindgen = "0.64"
regex = "1.8.3"
anyhow = {version = "1.0.66", features = ["default"]}

[dependencies]
libc = "0.2"
io-uring = "0.6.0"
serde = {version = "1.0.99", features = ["derive"]}
serde_json = "1.0.79"
bitmaps = "3.2.0"
log = {version = "0.4", features = ["release_max_level_off"]}
thiserror = "1.0.43"
derive_builder = "0.12"

[dev-dependencies]
block-utils = "0.11.0"
tempfile = "3.6.0"
regex = "1.8.4"
anyhow = {version = "1.0.66", features = ["default"]}
